# Generated by Django 4.1.7 on 2023-04-27 19:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='activities/')),
            ],
            options={
                'verbose_name_plural': 'Club',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('is_dean', models.BooleanField(default=False)),
                ('is_cfo', models.BooleanField(default=False)),
                ('is_club_mentor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('budget', models.FileField(upload_to='budget/')),
                ('event_poster', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('is_approved_by_dean', models.BooleanField(default=False)),
                ('is_approved_by_cfo', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('dean_reject_msg', models.TextField(max_length=800, null=True)),
                ('cfo_reject_msg', models.TextField(max_length=800, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events_add', to='portal.event'),
        ),
        migrations.AddField(
            model_name='club',
            name='factuly_incharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.member'),
        ),
    ]
