# Generated by Django 4.1.7 on 2023-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cfo_reject_msg',
            field=models.TextField(default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dean_reject_msg',
            field=models.TextField(default='', max_length=800, null=True),
        ),
    ]
